import { ClerkProvider } from "@clerk/nextjs";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import LeftSlider from './components/LeftSlider';
import RightSlider from './components/RightSlider';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
<ClerkProvider>
<html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >

<div className="w-[100%] h-fit flex justify-between">
  <div className="">
   <LeftSlider/>
  </div>
  
  <div>
  {children}

  </div>
<div className='w-[20%]'>
 <RightSlider/>
</div>
</div>

      </body>
    </html>
  </ClerkProvider>
  );
}
