import {  ClerkProvider } from "@clerk/nextjs";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import LeftSlider from './components/LeftSlider';
import RightSlider from './components/RightSlider';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
<ClerkProvider>
  
<html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >


  <div className="w-[100%] h-fit gap-10 flex justify-between">
  <div className="w-[25%] ">
   <LeftSlider/>
  </div>
  
  <div className="w-[50%] " >
  {children}

  </div>
<div className="w-[25%] ">
 <RightSlider/>
</div>
</div>



      </body>
    </html>
  </ClerkProvider>
  );
}
